#!/usr/bin/env python3
"""Generate the cross-project task index.

Usage:
  python3 tools/kb-tasks.py
  python3 tools/kb-tasks.py --write
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from datetime import date
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "_core" / "00-09_index" / "00.02-tasks.md"
ARCHIVES = REPO_ROOT / "archives"

DATE_RE = re.compile(r"Last updated:\s*(\d{4}-\d{2}-\d{2})")


def scan_files(root: Path) -> list[Path]:
    results: list[Path] = []

    for base in [root / "projects", root / "areas"]:
        if not base.exists():
            continue
        for path in sorted(base.rglob("*-moc.md")):
            if ARCHIVES in path.parents:
                continue
            results.append(path)

    for path in sorted(root.rglob("*.md")):
        if ARCHIVES in path.parents:
            continue
        if path.name == "AGENTS.md":
            continue
        if path in results:
            continue
        text = path.read_text(encoding="utf-8")
        if "<!-- kb-tasks:ignore -->" in text:
            continue
        if "<!-- kb-tasks:include -->" in text:
            results.append(path)

    return results


def extract_tasks(path: Path) -> tuple[list[tuple[int, str]], str | None]:
    text = path.read_text(encoding="utf-8")
    tasks = []
    for lineno, line in enumerate(text.splitlines(), 1):
        if line.startswith("- [ ] "):
            tasks.append((lineno, line[6:]))
    match = DATE_RE.search(text)
    return tasks, match.group(1) if match else None


def output_relative_link(path: Path) -> str:
    return Path(os.path.relpath(path, OUTPUT.parent)).as_posix()


def check_output_links() -> None:
    subprocess.run(
        [sys.executable, str(REPO_ROOT / "tools" / "check-links.py"), str(OUTPUT)],
        check=True,
    )


def generate(write: bool = False) -> str:
    sections: list[str] = []
    total = 0

    for path in scan_files(REPO_ROOT):
        tasks, last_updated = extract_tasks(path)
        if not tasks:
            continue
        rel = path.relative_to(REPO_ROOT)
        href = output_relative_link(path)
        header = (
            f"## [{rel.parent}]({href})"
            f" ({len(tasks)} task{'s' if len(tasks) != 1 else ''} / last updated {last_updated or 'unknown'})"
        )
        lines = [header]
        for lineno, text in tasks:
            lines.append(f"- [ ] {text}  <{rel.name}:{lineno}>")
        sections.append("\n".join(lines))
        total += len(tasks)

    body = "\n\n".join(sections) if sections else "No open tasks."
    content = f"""# Task Index (generated / kb-tasks.py)

> Open tasks: **{total}** / sources: **{len(sections)}**
> Source of truth is each project or area MOC. Do not edit this file manually.
> Generated: {date.today().isoformat()}

{body}
"""
    if write:
        OUTPUT.write_text(content, encoding="utf-8")
        print(f"Updated {OUTPUT.relative_to(REPO_ROOT)} ({total} tasks)", file=sys.stderr)
        check_output_links()
    return content


if __name__ == "__main__":
    write = "--write" in sys.argv
    output = generate(write=write)
    if not write:
        print(output, end="")
